classifiers:
  S: # robust classifier
    path_to_model: 'saved_models/evaluator/165228576343/100.pt'
    threshold: 0.1
    coeff: 10000
    approximate: True
  E: # manipulability classifier
    mi_coeff: 10000 # makes more like step function
    mi_threshold: 0.001 # manipulability score threshold
    t_threshold: 0.05 # translation distance for workspace
    q_threshold: 0.2 # quaternion distance for workspace
    w_coeff: 100000 # makes more like step function
  C: # collision classifier: at this moment only deals with table
    threshold: 0.001 # 0.175 for table # height of the table respect to the world frame
    coeff: 10 # sigmoid sharpening coefficient
    isTable: False # set false if not table, in that case need to pass pc of environme
    approximate: False # Works with pc_env -> gripper approximated as one bounding box. If True, then as 3 bbs
    base_extension: 0.2 # [m] extends base along local z axis to imitate panda's last joint.
    fill_between_fingers: True # fills between figers whem approximate is False.
  N: # NLP/intent classifier
    unused_param: 0.01
  T: # Tactile classifier
    unused_param: 0.01
  D: # top down classifier
    alpha_threshold: 0.9


optimizer:
 name: SGD # Multi Term Adam optimization MTAdam
 eta_t: 0.01 # Does not have meaning for not MT optimizer
 eta_r: 0.01
 grad_normalize: True
noise:
 eta_t: 0.0
 eta_r: 0.0
    
GraspOpt:
  1:
    classifiers: "S"
  2:
    classifiers: "C"
  # 3:
  #   classifiers: "N"
  # 3:
  #   classifiers: "D"
  # 2:
  #   classifiers: "EC"
  # 2:
  #   classifiers: "EC"

GraspOptESCfg:
  num_samples_per_grasp: 1 # do not modify
  es_freq: 3 # USELESS! ES runs at every es_freq steps 
  grad_iterations: 1 # Local gradient optimization
  t_std_dev: 0.05
  e_std_dev: 0.05
  S_warmup_iterations: 10 # number of warmup iterations for S
          
