classifiers:
  S: # robust classifier
    eta_t: 0.1 # lr on translations
    eta_r: 0.1 # lr on rotations
    path_to_model: 'saved_models/evaluator/165228576343/100.pt'
    threshold: 0.01
    coeff: 10000
    approximate: True
  E: # manipulability classifier
    eta_t: 0.1
    eta_r: 0.1
    mi_coeff: 10000 # makes more like step function
    mi_threshold: 0.001 # manipulability score threshold
    t_threshold: 0.05 # translation distance for workspace
    q_threshold: 0.2 # quaternion distance for workspace
    w_coeff: 100000 # makes more like step function
  C: # collision classifier: at this moment only deals with table
    eta_t: 0.1
    eta_r: 0.1
    threshold: 0.001 # 0.175 for table # height of the table respect to the world frame
    coeff: 10000 # sigmoid sharpening coefficient
    isTable: False # set false if not table, in that case need to pass pc of environme
    approximate: False # Works with pc_env -> gripper approximated as one bounding box. If True, then as 3 bbs
  N: # NLP/intent classifier
    eta_t: 0.01
    eta_r: 0.01
  T: # Tactile classifier
    eta_t: 0.01
    eta_r: 0.01
  D: # top down classifier
    alpha_threshold: 0.9
    eta_t: 0.01
    eta_r: 0.01

optimizer:
 name: SGD # Multi Term Adam optimization MTAdam
 eta_t: 0.01 # Does not have meaning for not MT optimizer
 eta_r: 0.01
 grad_normalize: True
noise:
 eta_t: 0.0
 eta_r: 0.0
    
GraspOpt:
  1:
    classifiers: "S"
  2:
    classifiers: "EC"
  3:
    classifiers: "N"
  4:
    classifier: "D"
  # 2:
  #   classifiers: "EC"
  # 2:
  #   classifiers: "EC"
GraspOptCfg:
  clip:
    use: False
    max: 0.1
    min: -0.1 # corresponds to ~0.11
  lower_bound:
    num_iterations: 1000 # initial iterations will use this

GraspOptESCfg:
  num_samples_per_grasp: 3 # do not modify
  es_freq: 10 # ES runs at every es_freq steps
  t_std_dev: 0.01
  e_std_dev: 0.01
  S_warmup_iterations: 5 # number of warmup iterations for S
          

# GraspOpt:
#   1:
#     classifiers: "SC"
#   # 2:
#   #   classifiers: "EC"
# GraspOptCfg:
#   clip:
#     use: False
#     max: 10000
#     min: -2.0 # corresponds to ~0.11
#   lower_bound:
#     num_iterations: 10 # initial iterations will use this