classifiers:
  S: # robust classifier
    eta_t: 0.01 # lr on translations
    eta_r: 0.01 # lr on rotations
    path_to_model: 'saved_models/evaluator/165228576343/100.pt'
  E: # manipulability classifier
    eta_t: 0.01
    eta_r: 0.01
    mi_coeff: 10000 # makes more like step function
    mi_threshold: 0.01 # manipulability score threshold
    t_threshold: 0.05 # translation distance for workspace
    q_threshold: 0.2 # quaternion distance for workspace
    w_coeff: 10000 # makes more like step function
  C: # collision classifier: at this moment only deals with table
    eta_t: 0.01
    eta_r: 0.01
    threshold: 0.175 # height of the table respect to the world frame
    coeff: 1000 # sigmoid sharpening coefficient
    isTable: True # set false if not table, in that case need to pass pc of environment
  N: # NLP/intent classifier
    eta_t: 0.01
    eta_r: 0.01
  T: # Tactile classifier
    eta_t: 0.01
    eta_r: 0.01
optimizer:
 name: SGD # Multi Term Adam optimization
 eta_t: 0.01 # Does not have meaning for not MT optimizer
 eta_r: 0.01
 grad_normalize: True
noise:
 eta_t: 0.0
 eta_r: 0.0
    